### ISSUE TITLE
Plugin removed from the Plugin Hub?

### ISSUE THREAD

**Issue by corrigami** [TheStonedTurtle/party-panel#11]
Quite liked using this plugin, what happened to it?

**Comment by zmike808** [comment]
Looks like it was disabled around a month ago, according to runelite git history, it set this plugin to "disabled=true" which I assume means disabled on plugin hub. I never got to use it but it looks very very useful. 

@TheStonedTurtle would you be ok with me forking this and trying to resubmit to plugin hub? Of course I'd give you all the proper credit still.

**Comment by corrigami** [comment]
It's back in, did you do anything @zmike808 ?
