### ISSUE TITLE
Always Show Sidebar unchecked but still there

### ISSUE THREAD

**Issue by WiggleNibble** [TheStonedTurtle/party-panel#18]
How to replicate bug : join party / create party then leave party. Hub Party Panel Sidebar is still visible after leaving.
Can only be fixed when you re-uncheck  the "Always Show Sidebar" or by restarting the plugin.
![image](https://user-images.githubusercontent.com/110086391/184285744-f9aa5a66-7f6f-43df-928e-fb192fea1ce1.png)
![image](https://user-images.githubusercontent.com/110086391/184285791-aa594257-b8b5-4818-b0fc-e062fdb357fd.png)

**Comment by TheStonedTurtle** [comment]
This has been fixed in edbfc5c4b41c96cd8db85b34b05c1590b4f2f3cd.

I will PR this change to RuneLite in a few days, I'd like to try and resolve #17 before releasing this change as well.

Thanks for the report!
