### ISSUE TITLE
Plugin removed from Plugin Hub again?

### ISSUE THREAD

**Issue by Hentiny** [TheStonedTurtle/party-panel#21]
Logged in today to find the plugin not on my sidebar, plugin list or the plugin hub. Other friends also noticed the same.

**Comment by runsbegone** [comment]
also cant find the plugin to install it right now

**Comment by TheStonedTurtle** [comment]
Adam has temporarily disabled this plugin as it was sending to much data and causing a fire on the server. I've been working on making the updates smaller so this plugin can be re-enabled. It should come back within a few days and definitely before ToA release.

**Comment by bagsly996** [comment]
ToA release was today, I know you guys are working hard but is there any update on when we will be seeing the plugin again?
