### ISSUE TITLE
unable to display live location 

### ISSUE THREAD

**Issue by reec3e** [TheStonedTurtle/party-panel#24]
looking for some help please. i am using hub party panel plugin, for live locations within  the group. everyone else is able to share there location except me. i have my discord and runelite logged in, linked to my account. i have logged out and in of everything. deleted the plugin and reinstalled and make sure all my privacy settings are correct. can anyone please help me. everyone else has their discord image displayed as it should be, mine is blank and black. 
![error in plugin](https://user-images.githubusercontent.com/122233636/211218484-efc36f41-9068-4a10-bf19-5f84f7e9bd97.png)

**Comment by TheStonedTurtle** [comment]
The image you are showing does not show the Hub Party Panel but the Vanilla RuneLite one. Any issues with integration with the Party system and discord would also be something for the RuneLite team to investigate. The only thing this plugin does is display a side panel with additional information, which has a blue icon instead of white, which means the live location feature you are asking about must be a vanilla feature.

**Comment by reec3e** [comment]
Hi mate, thanks for your response. The image is from party only but it’s your plugin that displays that image too. 

After doing the following it worked last night but after loading up again this morning still didn’t work.

I logged out of discord, closed the app. 
logged out of runelite, closed the app and reopened it while not logged into my runelite account. Logged into discord with no runelite login and downloaded the plugin and it worked. Then closed everything, logged back into runelite and it worked for the remainder of the evening until this morning.

**Comment by TheStonedTurtle** [comment]
The party system that RuneLite developed and maintains provides my plugin with the image (if it exists). All of the party functionality that exists in the base client is just reused in mine without any modifications. The only thing this plugin does it track and transmit additional information that you do not see in the base plugin (like inventory, equipment, prayer, levels, run energy, etc)

Pretty much anything that exists in the base RL party panel I do not modify or request myself and is instead grabbed from the source RL provides.
