### ISSUE TITLE
not showing in side panel

### ISSUE THREAD

**Issue by solodeicide** [TheStonedTurtle/party-panel#25]
I have the plugin installed but it's not showing in the side panel. It did show before, just recently it's disappeared. I have tried to uninstall and re-install and nothing changed.

**Comment by TheStonedTurtle** [comment]
![image](https://github.com/TheStonedTurtle/party-panel/assets/29030969/6b63dd58-bb83-4fa9-b7ab-f871b34fc469)
Make sure this option is selected, otherwise the side panel will only show up when you're in a party

**Comment by solodeicide** [comment]
It doesn't appear in my settings. I go to the plugin hub and shows it's installed but if I search my settings it's not in there.

**Comment by TheStonedTurtle** [comment]
You may need to share you `client.log` file then, it should show up as `Hub Party Panel` in the plugin list after it's installed.

This may also be something that needs to be escalated to the main RL team.

**Comment by solodeicide** [comment]
[client.log](https://github.com/TheStonedTurtle/party-panel/files/11482651/client.log)
is this what you wanted me to share? this is the most recent log.

**Comment by TheStonedTurtle** [comment]
@solodeicide it says that access is denied to the jar file inside `.runelite\plugins`, try deleting it, it should be named `party-panel3a58a2768eab1b561feb15371364ceb415fbd483.jar` and see if it redownloads properly. If not I'll have to ask the RL team what could cause this.

**Comment by solodeicide** [comment]
Thank you i did what you said and it resolved the problem =D
