### ISSUE TITLE
Remove case sensitivity

### ISSUE THREAD

**Issue by pettrs** [TheStonedTurtle/party-panel#27]
there are enough channels, and case sensitivity isn't an issue. if there's a privacy concern maybe add password protection instead somehow?

case sensitivity leads to more confusion than advantages. Pretty much everyone uses all small letters as default, but if you type the party name alone in chat, it will automatically appear with the first letter capitalized. Players are split over party "Example" and "example", especially people new to the plugin.

![image](https://github.com/TheStonedTurtle/party-panel/assets/75093127/c74b8118-9b67-4873-8d0c-66f46d877d49)

**Comment by TheStonedTurtle** [comment]
This request would be better made to the RuneLite team directly as they control the party system. The ability to join a plugin through the hub UI is purely for convenience and matches what the RL team is doing in their default Party plugin.

See https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPanel.java#L150-L182 for how they're doing it and https://github.com/TheStonedTurtle/party-panel/blob/master/src/main/java/thestonedturtle/partypanel/PartyPanelPlugin.java#L604-L626 for how we're doing it. The only difference (as of writing this) is the check for null.

**Comment by gftabor** [comment]
https://github.com/runelite/runelite/pull/18020

Made a few tiny changes, I will update my branch here
