### ISSUE TITLE
Bug: holding ctrl+shift and clicking a tile sometimes causes ctrl-lock like behavior

### ISSUE THREAD

**Issue by 4tet** [TheStonedTurtle/party-panel#30]
To reproduce, holding ctrl and shift and click a tile while in a party to ping a tile, then release both keys. Now click on a tile to walk there, but instead of walking there I'm finding that about half the time I end up pinging the tile even though I'm no longer holding the ctrl key. It nearly got me killed at ToB when I accidentally held both keys down while trying to shift click on a tile to walk there.

**Comment by TheStonedTurtle** [comment]
This plugin does not control the ping functionality, this is most likely a core RL party system issue.

**Comment by 4tet** [comment]
Thanks, created an issue there runelite/runelite#17478
