### ISSUE TITLE
Add Chat

### ISSUE THREAD

**Issue by MatthewLoller** [TheStonedTurtle/party-panel#34]
Wondering if there could be a simple chat added to a current party session.

Lots of scenarios of joining random groups where party is used but non needing to communicate over discord or fc.

Thanks!

**Comment by TheStonedTurtle** [comment]
This feature would require me to send every chat message through the Party Service which would use RL resources and cost Adam money. This seems like a poor use of RL resources when OSRS already provides this functionality via friends chats & clan chats. Just have everyone in the party join a friends chat.
