### ISSUE TITLE
Party Hub Panel Map Location not working

### ISSUE THREAD

**Issue by ijonasb** [TheStonedTurtle/party-panel#36]
I use three machines to play RuneScape: a laptop, a personal PC, and my work PC. None of them show the Party Hub panel location on the map. We’ll all be in the same party, and everyone else can see each other, but I can't see anyone's location, and no one can see mine. I've gone through the settings and asked friends for help, but we can't figure out the issue. My location never shows, and my friends can't see where I am either.

I’ve tried uninstalling the Party Hub plugin, created a new RuneLite profile, re-downloaded the Party Panel plugin, but the location still doesn’t show. How do I fix this?

**Comment by TheStonedTurtle** [comment]
That feature comes from the RuneLite Party System, not the Hub Party Plugin. Try turning off the hub, then the RL party plugin and then turning them back on (RL party then Hub party). That should solve your problem.

**Comment by TheStonedTurtle** [comment]
Closing this ticket as it's related to the RL Core Party plugin and not this one.
