### ISSUE TITLE
Users in party show up as "not logged in" and have missing info

### ISSUE THREAD

**Issue by bigdrizzle13** [TheStonedTurtle/party-panel#37]
Some users show up as "not logged in" and their stats (and other things) just show as default values.
<img width="255" alt="IMG_0237" src="https://github.com/user-attachments/assets/ebed2649-dd35-4a0e-a28e-9c884a742592">

**Comment by TheStonedTurtle** [comment]
This should have been resolved in 0e22c891b68ccc33a7fa2a831dd8c8ceedd1eec2, once the plugin has been updated to 3.3.1 this should be resolved.

**Comment by bigdrizzle13** [comment]
thank you, ill test when its released

**Comment by bigdrizzle13** [comment]
Same issue on 3.3.1

<img width="242" alt="image" src="https://github.com/user-attachments/assets/10286f16-a32a-480d-a379-7f0b667cd8a3">

<img width="242" alt="image" src="https://github.com/user-attachments/assets/37b7f0f1-3e6c-4dab-9d8c-54c3853780bb">

**Comment by TheStonedTurtle** [comment]
> Same issue on 3.3.1
> 
> <img alt="image" width="242" src="https://private-user-images.githubusercontent.com/20672745/373444018-10286f16-a32a-480d-a379-7f0b667cd8a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTkyNjAsIm5iZiI6MTcyNzk5ODk2MCwicGF0aCI6Ii8yMDY3Mjc0NS8zNzM0NDQwMTgtMTAyODZmMTYtYTMyYS00ODBkLWEzNzktN2YwYjY2N2NkOGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDIzNDI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMzgyMDdiODJjZTA0MmRjMGQyYTNlYThiMjljMTZhYTkxYWZmY2IzYTQ4ZmJlYjc2MGIzN2E0Mjc0M2VkYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J7oNAWawMMFuhMHB64-SyjC7BUfTJlZlILKWe7pj554"> <img alt="image" width="242" src="https://private-user-images.githubusercontent.com/20672745/373444062-37b7f0f1-3e6c-4dab-9d8c-54c3853780bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTkyNjAsIm5iZiI6MTcyNzk5ODk2MCwicGF0aCI6Ii8yMDY3Mjc0NS8zNzM0NDQwNjItMzdiN2YwZjEtM2U2Yy00ZGFiLTlkOGMtNTRjMzg1Mzc4MGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDIzNDI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5N2M3ZDYyNzM3M2EyNmNiNTkzYWJhZjk5MTJhZGQ4MjAyODYyMjgzNjcyNGFjNmQzNjM4MjgyNDMwYjI0OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4TXqXorlc9A3WKLx-ZxEhWaKdfqJX5J1UNjTuOjCgZk">

Can you confirm that the other user is also on v3.3.1? Due to the nature of this plugin everyone needs to be using the same version otherwise weird bugs can happen.

This plugin handles sending your data to other players as well as displaying other players data on your client. In this case both of these were experiencing issues. If someone is on an older version the code they're running that handles the sending of data to other players could still be broken.

**Comment by bigdrizzle13** [comment]
The other person is just me on another runelite instance. Also on 3.1.1. Let me try to refresh all my clients to make sure something isn't stale here.

**Comment by TheStonedTurtle** [comment]
Okay, attempt number 2 at fixing this problem via 9ffe7b14d0023c027ed7d3b45772504d31a9de4e. Please wait for v3.3.2 to be merged and let me know if the issue still exists. 

Apparently trying to fix some lag caused be re-renders and adding the RunePouch contents broke more things than it fixed :/

**Comment by TheStonedTurtle** [comment]
@bigdrizzle13 v3.3.2 is now live, let me know if you still experience this.

**Comment by TheStonedTurtle** [comment]
Closing this as I believe this has been resolved, if its still an issue please open a new issue.
