### ISSUE TITLE
Keep the party panel icon visible 

### ISSUE THREAD

**Issue by Jilms** [TheStonedTurtle/party-panel#5]
Sometimes the party plugin that is in RuneLite bugs out and I need to restart my client to leave the party that I'm in by myself. It would be nice to just have the button there constantly so I can click the leave party button if it bugs out, also sometimes I will be in a party and the party panel button won't show up but everything else about the party will work so I have to leave their party and restart my client and join the party back for the button to show up in the panel on the right side. So keeping the party panel button visible at all times while the plugin is enabled should solve the problem I'm having I think or at least make this a configurable option to always show the icon/button. Thanks :)

**Comment by TheStonedTurtle** [comment]
A config toggle has been added in commit c69da35ca2265b39c16cd3eb9a1ef8f77f0305f9
