### ISSUE TITLE
Wanted to chat with you about Party Panel 

### ISSUE THREAD

**Issue by beaudryj** [TheStonedTurtle/party-panel#7]
No email or anything on your profile wanted to reach out and chat about your plugin with some ideas and wanting to contribute. @TheStonedTurtle

**Comment by TheStonedTurtle** [comment]
If you want to add something to the plugin you can fork the repository and make a pull request. You can also create an Feature Request issue and just mention that you are willing to implement the feature and I'll respond to it.

You can also find me on Discord as `TheStonedTurtle#8786`. I'm also in the RL discord so you can just @ me in #general.
